// Fixed scenarios for each use case. Not editable in the UI to keep demo runs predictable.

export const SCENARIOS = {
  uc1: `A leading GCC operator, acting as prime for a national mission-critical end customer, has issued an RFI for an Ericsson Integrated Core Solution and requests an indicative budgetary quotation within seven working days. The scope is a dedicated, logically isolated private 4G/5G dual-mode core for the Mission Critical Networks segment, deployed cloud-native on the operator's premises across two geo-redundant sites at 99.99% availability. The operator reuses its existing RAN and spectrum. Ericsson provides the core, no RAN. The core is dimensioned over a multi-year horizon for up to approximately 20,000 provisioned and active users, with a phased growth path to higher capacity. It includes a Compact IMS for private voice (VoLTE) for up to approximately 5,000 active users, at least 40 Gbps active core throughput, and the CNIS cloud platform. The service mix spans mission-critical push-to-talk and push-to-video, native voice, and private data and IoT. Scope covers solution design, deployment, integration, testing, acceptance, and go-live. The operator expects a term-based licence model and a multi-year TCO, and is open to a longer commitment if it improves the commercial construct. Generate the budgetary quotation package: pricing schedule, solution description, and statement of compliance to the stated requirements.`,

  uc2: `A leading GCC operator has requested a 10% list-price reduction on a roughly $6M Integrated Core Solution deal for its Mission Critical Networks segment, citing Nokia competitive pressure. They want to close before Q4. How should we respond?`,

  uc3: `The customer has returned the framework agreement with deviations on the following Business-Critical Terms: liability cap proposed at 50% of contract value (vs. Ericsson wanted 100%); indexation cap proposed at 2% (vs. Ericsson wanted uncapped or 5%); 3PP cost pass-through proposed as fixed at signing (vs. Ericsson wanted full pass-through); termination for convenience proposed with 60-day notice and no cancellation fees (vs. Ericsson wanted 180-day notice with cancellation structure); IP indemnity scope proposed to include customer-supplied specifications (vs. Ericsson wanted standard carve-outs). Assess each deviation against Ericsson's wanted position, identify the priority deviations to push back on hardest, and recommend a negotiation strategy with suggested redline language for the top three.`,
};
