// Fixed scenarios for each use case. Not editable in the UI to keep demo runs predictable.

export const SCENARIOS = {
  uc1: `A leading GCC operator, acting as prime for a national mission-critical end customer, has issued an RFI for an Ericsson Integrated Core Solution and requests an indicative budgetary quotation within seven working days. The scope is a dedicated, logically isolated private 4G/5G dual-mode core for the Mission Critical Networks segment, deployed cloud-native on the operator's premises across two geo-redundant sites at 99.99% availability. The operator reuses its existing RAN and spectrum. Ericsson provides the core, no RAN. The core is dimensioned over a multi-year horizon for up to approximately 20,000 provisioned and active users, with a phased growth path to higher capacity. It includes a Compact IMS for private voice (VoLTE) for up to approximately 5,000 active users, at least 40 Gbps active core throughput, and the CNIS cloud platform. The service mix spans mission-critical push-to-talk and push-to-video, native voice, and private data and IoT. Scope covers solution design, deployment, integration, testing, acceptance, and go-live. The operator expects a term-based licence model and a multi-year TCO, and is open to a longer commitment if it improves the commercial construct. Generate the budgetary quotation package: pricing schedule, solution description, and statement of compliance to the stated requirements.`,

  uc2: `A leading GCC operator has requested a 10% list-price reduction on a roughly $6M Integrated Core Solution deal for its Mission Critical Networks segment, citing Nokia competitive pressure. They want to close before Q4. How should we respond?`,

  uc3: `A leading GCC operator has returned the multi-year framework agreement for the Integrated Core Solution. It has deviated from Ericsson's wanted position on the Business-Critical Terms below.

| BCTC | What the customer returned | Ericsson wanted position |
|------|----------------------------|--------------------------|
| BCTC-04 Relief from performance | No relief or extension of time for customer failures or inaccurate assumptions, no reimbursement of customer-caused costs. | Relief, extensions of time and cost recovery for customer failures and inaccurate assumptions. |
| BCTC-12 Assignability and transfer | No express Ericsson right to assign or factor receivables, and assignment to third parties is restricted. | Right to assign or factor receivables, customer consent not unreasonably withheld, and no customer assignment without Ericsson consent. |
| BCTC-13 Set-off and late payment interest | Customer may set off amounts it claims against Ericsson invoices, and Ericsson has no right to late payment interest. | No customer set-off, and a right to charge late payment interest. |
| BCTC-15 Termination and suspension rights | No unilateral Ericsson right to terminate on a customer change of control, only a good faith discussion. | Unilateral right to terminate on the customer's change of control. |
| BCTC-17 Limitation of liability | Single cap does not clearly cover service credits and penalties, and leaves the third party IPR indemnity uncapped. Only a general exclusion of indirect loss, without the enumerated categories. | One cap across all liabilities including indemnities, LDs, service credits and penalties, plus the full list of excluded indirect and consequential loss. |
| BCTC-18 Delays | LDs not stated as the sole and exclusive financial remedy for delay. | LDs as the sole financial remedy, inside the cap, with no double recovery. |
| BCTC-21 IPR indemnity | Indemnity not capped by the liability cap, not limited to court awarded damages, weak Ericsson control of defence and settlement, no clear modify, replace or refund remedy, combinations not excluded. | Indemnity confined to the standard carve-outs and capped by the general cap, as the exclusive IPR remedy. |
| BCTC-22 Data access, ownership and use rights | Customer will not accept sharing network data, denying Ericsson the access and use rights needed to deliver and support the core. | Rights to access, store, use, process and transfer the data to perform the agreement, with secure access through CAS or MSDP. |

Assess each deviation against Ericsson's wanted position, assign a severity, identify the priority deviations to push back on hardest, and recommend a negotiation strategy with suggested redline language for the top three.`,
};
