// Fixed scenarios for each use case. Not editable in the UI to keep demo runs predictable.

export const SCENARIOS = {
  uc1: `A leading GCC operator, acting as prime for a national mission-critical end customer, has issued an RFI for an Integrated Core Solution: a dedicated, logically isolated private 4G/5G dual-mode core for the Mission Critical Networks segment, requesting an indicative budgetary quotation within seven working days. The scope is a cloud-native core deployed on the customer's premises, reusing the operator's existing RAN and spectrum, geo-redundant 1+1 across two sites at 99.99% availability. It is dimensioned over the contract horizon for up to approximately 20,000 provisioned and active users, voice (VoLTE / IMS) for up to approximately 5,000 active users, and at least 40 Gbps active core throughput with a defined scaling path. It supports mission-critical communications (push-to-talk and push-to-video), native voice, and private data and IoT, plus solution design, deployment, integration, testing, acceptance, and go-live services. The customer is open to a multi-year commitment if it improves the commercial proposition. Generate the budgetary quotation package: pricing schedule, solution description, and statement of compliance to the customer's stated requirements.`,

  uc2: `A leading GCC operator has requested a 10% list-price reduction on a roughly $6M Integrated Core Solution deal for its Mission Critical Networks segment, citing Nokia competitive pressure. They want to close before Q4. How should we respond?`,

  uc3: `The customer has returned the framework agreement with deviations on the following Business-Critical Terms: liability cap proposed at 50% of contract value (vs. Ericsson wanted 100%); indexation cap proposed at 2% (vs. Ericsson wanted uncapped or 5%); 3PP cost pass-through proposed as fixed at signing (vs. Ericsson wanted full pass-through); termination for convenience proposed with 60-day notice and no cancellation fees (vs. Ericsson wanted 180-day notice with cancellation structure); IP indemnity scope proposed to include customer-supplied specifications (vs. Ericsson wanted standard carve-outs). Assess each deviation against Ericsson's wanted position, identify the priority deviations to push back on hardest, and recommend a negotiation strategy with suggested redline language for the top three.`,
};
